### ISSUE TITLE
Add `Social Providers` to the list of parameters

### ISSUE THREAD

**Issue by teamtelnet** [IUCCA/ansible-role-tandoor#3]
Would be nice if you could add these two parameters so it would be possible to configure a OIDC Provider with this ansible role.

```
SOCIAL_PROVIDERS=allauth.socialaccount.providers.openid_connect
SOCIALACCOUNT_PROVIDERS='{"openid_connect":{"APPS":[{"provider_id":"keycloak","name":"Keycloak","client_id":"KEYCLOAK_CLIENT_ID","secret":"KEYCLOAK_CLIENT_SECRET","settings":{"server_url":"https://auth.example.org/realms/KEYCLOAK_REALM/.well-known/openid-configuration"}}]}}'
```

[Tandoor Doc](https://docs.tandoor.dev/features/authentication/)

**Comment by IUCCA** [comment]
You can add both locally via the variable tandoor_container_additional_environment_variables. I don't use an OIDC provider myself, so I can't test this and don't know exactly how to set the parameter so that the connection works out of box with the playbook's OIDC provider. Feel free to create a PR, or share the parameters that have a query whether oidc is used in the playbook and if so, how this must be configured.

**Comment by teamtelnet** [comment]
I hadn’t realized that the variable `tandoor_container_additional_environment_variables` could be used for this purpose. I’ve added the variables using this function now. Sorry for raising it, and thank you for your quick help!
